services:
  - type: web
    name: smart-learn-react
    runtime: node
    buildCommand: |
      cd SmartLearn-React/frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node SmartLearn-React/backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
